import type { User, Order, DailyAnalytics, MonthlyAnalytics } from "@/types";

export const mockUsers: User[] = [
  {
    id: "student1",
    email: "student@assignly.com",
    role: "student",
    pageQuota: 32,
    quotaLastReplenished: new Date("2023-10-01T00:00:00Z"),
    totalOrdersPlaced: 5,
    totalPagesUsed: 8,
    createdAt: new Date("2023-09-01T10:00:00Z"),
    isActive: true,
    paymentStatus: "paid",
    lastPaymentDate: new Date("2023-10-01T10:00:00Z"),
    amountPaid: 100,
  },
  {
    id: "admin1",
    email: "admin@assignly.com",
    role: "admin",
    pageQuota: 999,
    quotaLastReplenished: new Date(),
    totalOrdersPlaced: 0,
    totalPagesUsed: 0,
    createdAt: new Date("2023-01-01T10:00:00Z"),
    isActive: true,
    paymentStatus: "paid",
    lastPaymentDate: null,
    amountPaid: 0,
  },
  {
    id: 'student2',
    email: 'test.student2@example.com',
    role: 'student',
    pageQuota: 15,
    quotaLastReplenished: new Date('2023-10-01T00:00:00Z'),
    totalOrdersPlaced: 10,
    totalPagesUsed: 25,
    createdAt: new Date('2023-05-15T12:00:00Z'),
    isActive: true,
    paymentStatus: 'pending',
    lastPaymentDate: new Date('2023-09-01T11:00:00Z'),
    amountPaid: 100,
  },
  {
    id: 'student3',
    email: 'another.one@example.com',
    role: 'student',
    pageQuota: 40,
    quotaLastReplenished: new Date('2023-10-01T00:00:00Z'),
    totalOrdersPlaced: 2,
    totalPagesUsed: 5,
    createdAt: new Date('2023-08-20T08:30:00Z'),
    isActive: true,
    paymentStatus: 'overdue',
    lastPaymentDate: new Date('2023-08-20T08:30:00Z'),
    amountPaid: 100,
  },
];

export const mockOrders: Order[] = [
  {
    id: "order1",
    studentId: "student1",
    studentEmail: "student@assignly.com",
    originalFileName: "History_Essay_Final.pdf",
    originalFileUrl: "#",
    googleDriveFileId: null,
    pageCount: 5,
    status: "completed",
    completedFileUrl: "#",
    completedGoogleDriveId: null,
    createdAt: new Date("2023-10-25T14:30:00Z"),
    startedAt: new Date("2023-10-25T16:00:00Z"),
    completedAt: new Date("2023-10-26T10:00:00Z"),
    turnaroundTimeHours: 20,
    notes: "Good work on the citations.",
  },
  {
    id: "order2",
    studentId: "student1",
    studentEmail: "student@assignly.com",
    originalFileName: "Lab_Report_Chemistry.docx",
    originalFileUrl: "#",
    googleDriveFileId: null,
    pageCount: 3,
    status: "in_progress",
    completedFileUrl: null,
    completedGoogleDriveId: null,
    createdAt: new Date("2023-10-26T18:00:00Z"),
    startedAt: new Date("2023-10-27T09:00:00Z"),
    completedAt: null,
    turnaroundTimeHours: null,
    notes: "Client needs this back by EOD tomorrow.",
  },
  {
    id: "order3",
    studentId: "student2",
    studentEmail: "test.student2@example.com",
    originalFileName: "presentation_slides.jpg",
    originalFileUrl: "#",
    googleDriveFileId: null,
    pageCount: 1,
    status: "pending",
    completedFileUrl: null,
    completedGoogleDriveId: null,
    createdAt: new Date("2023-10-27T11:00:00Z"),
    startedAt: null,
    completedAt: null,
    turnaroundTimeHours: null,
    notes: null,
  },
  {
    id: 'order4',
    studentId: 'student3',
    studentEmail: 'another.one@example.com',
    originalFileName: 'Calculus_Homework_Set3.pdf',
    originalFileUrl: '#',
    googleDriveFileId: null,
    pageCount: 12,
    status: 'pending',
    completedFileUrl: null,
    completedGoogleDriveId: null,
    createdAt: new Date('2023-10-27T12:00:00Z'),
    startedAt: null,
    completedAt: null,
    turnaroundTimeHours: null,
    notes: 'Urgent request.',
  },
];

export const mockDailyAnalytics: DailyAnalytics[] = Array.from({ length: 30 }).map((_, i) => {
    const date = new Date();
    date.setDate(date.getDate() - i);
    const ordersReceived = Math.floor(Math.random() * 10) + 5;
    const ordersCompleted = Math.floor(Math.random() * ordersReceived);
    return {
        id: `daily_${date.toISOString().slice(0, 10).replace(/-/g, '_')}`,
        date,
        ordersReceived,
        ordersCompleted,
        pagesProcessed: ordersCompleted * (Math.floor(Math.random() * 5) + 3),
        totalOrders: 0,
        completedOrders: 0,
        pendingOrders: 0,
        totalPagesProcessed: 0,
        averageTurnaroundHours: 0,
        activeStudents: 0,
    }
}).reverse();

export const mockMonthlyAnalytics: MonthlyAnalytics[] = [
    { id: 'monthly_2023_09', month: 'September 2023', totalOrders: 150, totalPagesProcessed: 750, averageTurnaroundHours: 28, completedOrders: 145, pendingOrders: 5, activeStudents: 38 },
    { id: 'monthly_2023_10', month: 'October 2023', totalOrders: 180, totalPagesProcessed: 910, averageTurnaroundHours: 25, completedOrders: 170, pendingOrders: 10, activeStudents: 40 },
]
